"""Frame parsing in the probe, checked against frames pymavlink built.

No socket is opened anywhere in this file. Every frame is generated by
pymavlink and then handed to the probe's own parser, so the assertions compare
our reading of the wire format against the reference implementation rather than
against bytes someone typed out by hand.

That matters most for `extract_param_id`. MAVLink orders payload fields by
descending type size rather than declaration order, so the offset of param_id
is easy to get wrong and impossible to notice: a wrong offset yields a
plausible-looking string, the roundtrip probe never matches it, and the link
gets recorded as telemetry-only forever without anyone learning why.
"""

from __future__ import annotations

import ast
import warnings
from pathlib import Path

import pytest
from pymavlink.dialects.v10 import ardupilotmega as mav1
from pymavlink.dialects.v20 import ardupilotmega as mav2

from tools import mavlink_probe
from tools.mavlink_probe import (
    EVENT_DRIVEN,
    HEARTBEAT_PAYLOAD_LEN,
    MAV_AUTOPILOT_INVALID,
    MAV_TYPE_GCS,
    MAVLINK_V1_MAGIC,
    MAVLINK_V2_MAGIC,
    MESSAGE_NAMES,
    MIN_SAMPLES_FOR_RATE,
    MIN_SPAN_FOR_RATE_S,
    NON_VEHICLE_MAV_TYPES,
    PARAM_VALUE_MSGID,
    REQUIRED_STREAMS,
    classify_absences,
    classify_source,
    compute_rate_hz,
    decode_header,
    extract_param_id,
    parse_heartbeat,
    payload_of,
    resolve_message_name,
    split_frames,
)

SYSID = 7
COMPID = 1


def _v2_link(sysid: int = SYSID, compid: int = COMPID) -> mav2.MAVLink:
    link = mav2.MAVLink(None, srcSystem=sysid, srcComponent=compid)
    link.signing.sign_outgoing = False
    return link


def _v1_link(sysid: int = SYSID, compid: int = COMPID) -> mav1.MAVLink:
    return mav1.MAVLink(None, srcSystem=sysid, srcComponent=compid)


def heartbeat_v2(sysid: int = SYSID) -> bytes:
    link = _v2_link(sysid)
    message = mav2.MAVLink_heartbeat_message(
        type=mav2.MAV_TYPE_QUADROTOR,
        autopilot=mav2.MAV_AUTOPILOT_ARDUPILOTMEGA,
        base_mode=0,
        custom_mode=0,
        system_status=mav2.MAV_STATE_STANDBY,
        mavlink_version=3,
    )
    return bytes(message.pack(link))


def heartbeat_v1(sysid: int = SYSID) -> bytes:
    link = _v1_link(sysid)
    message = mav1.MAVLink_heartbeat_message(
        type=mav1.MAV_TYPE_QUADROTOR,
        autopilot=mav1.MAV_AUTOPILOT_ARDUPILOTMEGA,
        base_mode=0,
        custom_mode=0,
        system_status=mav1.MAV_STATE_STANDBY,
        mavlink_version=3,
    )
    return bytes(message.pack(link))


def param_value_v2(param_id: str, sysid: int = SYSID) -> bytes:
    link = _v2_link(sysid)
    message = mav2.MAVLink_param_value_message(
        param_id=param_id.encode("ascii"),
        param_value=1.0,
        param_type=mav2.MAV_PARAM_TYPE_INT32,
        param_count=800,
        param_index=42,
    )
    return bytes(message.pack(link))


def param_value_v1(param_id: str, sysid: int = SYSID) -> bytes:
    link = _v1_link(sysid)
    message = mav1.MAVLink_param_value_message(
        param_id=param_id.encode("ascii"),
        param_value=1.0,
        param_type=mav1.MAV_PARAM_TYPE_INT32,
        param_count=800,
        param_index=42,
    )
    return bytes(message.pack(link))


def sign_v2_frame(frame: bytes) -> bytes:
    """Set the signing flag and append a 13-byte signature block.

    The probe never validates a signature; it only has to account for the extra
    bytes when deciding where a frame ends. A block of the right length is
    therefore a faithful fixture for the only property under test.
    """
    body = bytearray(frame)
    body[2] |= 0x01  # incompat_flags: MAVLINK_IFLAG_SIGNED
    return bytes(body) + bytes(range(13))


# --- split_frames -----------------------------------------------------------


def test_single_frame_round_trips() -> None:
    frame = heartbeat_v2()

    assert split_frames(frame) == [frame]


def test_multi_frame_datagram_is_split_exactly() -> None:
    """QGC coalesces several MAVLink frames into one UDP datagram."""
    first = heartbeat_v2(sysid=1)
    second = param_value_v2("SYSID_THISMAV", sysid=2)
    third = heartbeat_v1(sysid=3)

    assert split_frames(first + second + third) == [first, second, third]


def test_truncated_trailing_frame_is_dropped_not_guessed() -> None:
    """A short final frame must be discarded, and the whole ones kept."""
    whole = heartbeat_v2()
    truncated = param_value_v2("SYSID_THISMAV")[:-4]

    assert split_frames(whole + truncated) == [whole]


def test_truncated_frame_alone_yields_nothing() -> None:
    assert split_frames(heartbeat_v2()[:-1]) == []


def test_signed_v2_frame_length_accounts_for_the_signature() -> None:
    """The signing flag adds 13 bytes; miscounting them desynchronises the rest."""
    signed = sign_v2_frame(heartbeat_v2(sysid=1))
    following = heartbeat_v2(sysid=2)

    assert split_frames(signed + following) == [signed, following]


def test_garbage_before_a_valid_frame_is_resynchronised() -> None:
    frame = heartbeat_v2()

    assert split_frames(b"\x00\x11\x22garbage" + frame) == [frame]


def test_garbage_only_yields_nothing() -> None:
    assert split_frames(b"no mavlink here") == []


def test_empty_input_yields_nothing() -> None:
    assert split_frames(b"") == []


# --- decode_header ----------------------------------------------------------


def test_decode_header_v2() -> None:
    header = decode_header(param_value_v2("SYSID_THISMAV", sysid=11))

    assert header == (11, COMPID, PARAM_VALUE_MSGID)


def test_decode_header_v1() -> None:
    header = decode_header(param_value_v1("SYSID_THISMAV", sysid=11))

    assert header == (11, COMPID, PARAM_VALUE_MSGID)


def test_decode_header_v1_and_v2_agree() -> None:
    """Version must not change the identity the Gateway keys vehicles on."""
    assert decode_header(heartbeat_v1(sysid=5)) == decode_header(heartbeat_v2(sysid=5))


def test_decode_header_on_signed_frame() -> None:
    signed = sign_v2_frame(param_value_v2("SYSID_THISMAV", sysid=9))

    assert decode_header(signed) == (9, COMPID, PARAM_VALUE_MSGID)


@pytest.mark.parametrize("length", [0, 1, 5, 7])
def test_decode_header_rejects_short_input(length: int) -> None:
    assert decode_header(heartbeat_v2()[:length]) is None


def test_decode_header_rejects_unknown_magic() -> None:
    assert decode_header(b"\x00" * 16) is None


# --- payload_of -------------------------------------------------------------


def test_payload_of_v2_matches_the_declared_length() -> None:
    frame = param_value_v2("SYSID_THISMAV")

    payload = payload_of(frame)

    assert payload is not None
    assert len(payload) == frame[1]


def test_payload_of_signed_frame_excludes_the_signature() -> None:
    """Slicing back from the end would swallow signature bytes as payload."""
    unsigned = param_value_v2("SYSID_THISMAV")
    signed = sign_v2_frame(unsigned)

    assert payload_of(signed) == payload_of(unsigned)


def test_payload_of_rejects_a_truncated_payload() -> None:
    assert payload_of(param_value_v2("SYSID_THISMAV")[:-6]) is None


def test_payload_of_rejects_unknown_magic() -> None:
    assert payload_of(b"\x01\x02\x03\x04") is None


# --- extract_param_id -------------------------------------------------------

PARAM_NAMES = [
    "SYSID_THISMAV",
    "BATT_CAPACITY",
    "A",  # shortest plausible name
    "FENCE_ALT_MAX",
    "RTL_ALT",
]


@pytest.mark.parametrize("name", PARAM_NAMES)
def test_extract_param_id_v2(name: str) -> None:
    assert extract_param_id(param_value_v2(name)) == name


@pytest.mark.parametrize("name", PARAM_NAMES)
def test_extract_param_id_v1(name: str) -> None:
    assert extract_param_id(param_value_v1(name)) == name


def test_extract_param_id_v1_and_v2_agree() -> None:
    name = "SYSID_THISMAV"

    assert extract_param_id(param_value_v1(name)) == extract_param_id(
        param_value_v2(name)
    )


def test_extract_param_id_handles_a_full_16_character_name() -> None:
    """A name filling the field has no NUL terminator to stop at."""
    name = "ABCDEFGHIJKLMNOP"
    assert len(name) == 16

    assert extract_param_id(param_value_v2(name)) == name


def test_extract_param_id_survives_v2_payload_truncation() -> None:
    """v2 trims trailing zero bytes; the parser must restore them."""
    frame = bytearray(param_value_v2("RTL_ALT"))
    # Drop the trailing zero bytes the way an encoder doing full truncation
    # would, leaving a payload shorter than the 25-byte PARAM_VALUE definition.
    payload_len = frame[1]
    assert payload_len >= 24

    assert extract_param_id(bytes(frame)) == "RTL_ALT"


def test_extract_param_id_on_signed_frame() -> None:
    signed = sign_v2_frame(param_value_v2("SYSID_THISMAV"))

    assert extract_param_id(signed) == "SYSID_THISMAV"


def test_extract_param_id_returns_none_for_non_ascii() -> None:
    """An unreadable name is a failure, never a wildcard match."""
    frame = bytearray(param_value_v2("SYSID_THISMAV"))
    frame[10 + 8] = 0xFF  # first byte of param_id

    assert extract_param_id(bytes(frame)) is None


def test_extract_param_id_returns_none_for_an_empty_name() -> None:
    frame = bytearray(param_value_v2("SYSID_THISMAV"))
    for offset in range(8, 24):
        frame[10 + offset] = 0x00

    assert extract_param_id(bytes(frame)) is None


def test_extract_param_id_returns_none_on_a_truncated_frame() -> None:
    assert extract_param_id(param_value_v2("SYSID_THISMAV")[:-6]) is None


def test_param_id_offset_matches_the_reference_encoder() -> None:
    """Pin the offset itself, not just the round trip.

    If MAVLink's field ordering is ever misremembered again, this fails with a
    message that says what the real layout is.
    """
    name = "SYSID_THISMAV"
    payload = payload_of(param_value_v2(name))

    assert payload is not None
    assert payload.index(name.encode("ascii")) == 8, (
        "param_id does not start at offset 8; MAVLink orders payload fields by "
        "descending type size, so re-derive the layout before changing the "
        "constants in mavlink_probe.py"
    )


# --- the parsers agree with each other --------------------------------------


def test_param_value_survives_a_realistic_coalesced_datagram() -> None:
    """The end-to-end path roundtrip mode depends on, without a socket."""
    datagram = (
        heartbeat_v2(sysid=1)
        + param_value_v2("SYSID_THISMAV", sysid=1)
        + heartbeat_v1(sysid=2)
    )

    names = [
        extract_param_id(frame)
        for frame in split_frames(datagram)
        if (header := decode_header(frame)) is not None
        and header[2] == PARAM_VALUE_MSGID
    ]

    assert names == ["SYSID_THISMAV"]


def test_magic_constants_match_the_reference_encoder() -> None:
    assert heartbeat_v2()[0] == MAVLINK_V2_MAGIC
    assert heartbeat_v1()[0] == MAVLINK_V1_MAGIC


# --- classify_absences ------------------------------------------------------

STATUSTEXT = 253
MISSION_ITEM_REACHED = 46
HEARTBEAT = 0
GLOBAL_POSITION_INT = 33


def test_statustext_is_not_treated_as_a_stream() -> None:
    """The regression this split exists for.

    STATUSTEXT arrives when the flight controller has something to say. On a
    parked, healthy aircraft it never arrives, and calling that MISSING sends
    someone tuning SR*_ parameters that were never the problem.
    """
    assert STATUSTEXT not in REQUIRED_STREAMS
    assert STATUSTEXT in EVENT_DRIVEN


def test_mission_item_reached_is_event_driven() -> None:
    """It fires on waypoint completion, so a stationary vehicle emits none."""
    assert MISSION_ITEM_REACHED not in REQUIRED_STREAMS
    assert MISSION_ITEM_REACHED in EVENT_DRIVEN


def test_the_two_groups_are_disjoint() -> None:
    assert not REQUIRED_STREAMS & EVENT_DRIVEN


@pytest.mark.parametrize("msgid", sorted(REQUIRED_STREAMS | EVENT_DRIVEN))
def test_every_classified_message_can_be_named_in_a_report(msgid: int) -> None:
    """An operator reading the output should see a name, not a bare number."""
    assert msgid in MESSAGE_NAMES


def test_quiet_link_produces_no_findings() -> None:
    """Every stream present and no events: nothing is wrong, so say nothing."""
    missing, unobserved = classify_absences(set(REQUIRED_STREAMS))

    assert missing == set()
    assert unobserved == EVENT_DRIVEN


def test_an_absent_stream_is_a_finding() -> None:
    seen = set(REQUIRED_STREAMS) - {GLOBAL_POSITION_INT}

    missing, _ = classify_absences(seen)

    assert missing == {GLOBAL_POSITION_INT}


def test_observed_events_are_not_reported_as_unobserved() -> None:
    seen = set(REQUIRED_STREAMS) | {STATUSTEXT}

    missing, unobserved = classify_absences(seen)

    assert missing == set()
    assert unobserved == {MISSION_ITEM_REACHED}


def test_a_silent_link_reports_every_stream_missing() -> None:
    missing, unobserved = classify_absences(set())

    assert missing == REQUIRED_STREAMS
    assert unobserved == EVENT_DRIVEN


def test_unrelated_traffic_does_not_satisfy_a_requirement() -> None:
    """Seeing plenty of some other message is not evidence the streams are on."""
    missing, _ = classify_absences({HEARTBEAT, 30, 32, 241})

    assert HEARTBEAT not in missing
    assert missing == REQUIRED_STREAMS - {HEARTBEAT}


# --- compute_rate_hz --------------------------------------------------------


def test_two_samples_in_the_same_millisecond_produce_no_rate() -> None:
    """The defect seen on hardware: COMMAND_ACK twice, reported as 54 kHz.

    Dividing by a near-zero span turns one event observed twice into a number
    that reads like a measurement. There is no rate here to report.
    """
    assert compute_rate_hz(count=2, span_s=0.001) is None


def test_two_samples_far_apart_still_produce_no_rate() -> None:
    """Two samples describe one interval, which is not a rate."""
    assert compute_rate_hz(count=2, span_s=60.0) is None


def test_zero_span_produces_no_rate() -> None:
    assert compute_rate_hz(count=10, span_s=0.0) is None


def test_burst_within_the_minimum_span_produces_no_rate() -> None:
    """A STATUSTEXT burst at boot is not a stream, however many arrive."""
    assert compute_rate_hz(count=25, span_s=0.2) is None


def test_a_genuine_stream_produces_a_rate() -> None:
    """40 samples across 10s is 39 intervals: 3.9 Hz."""
    assert compute_rate_hz(count=40, span_s=10.0) == pytest.approx(3.9)


def test_rate_uses_intervals_not_samples() -> None:
    """n samples bound n-1 intervals; using n inflates every rate."""
    assert compute_rate_hz(count=11, span_s=10.0) == pytest.approx(1.0)


def test_rate_is_reported_at_the_threshold() -> None:
    assert compute_rate_hz(count=MIN_SAMPLES_FOR_RATE, span_s=MIN_SPAN_FOR_RATE_S) == (
        pytest.approx((MIN_SAMPLES_FOR_RATE - 1) / MIN_SPAN_FOR_RATE_S)
    )


@pytest.mark.parametrize(
    ("count", "span_s"),
    [(MIN_SAMPLES_FOR_RATE - 1, 10.0), (10, MIN_SPAN_FOR_RATE_S - 0.01)],
)
def test_rate_is_withheld_just_below_each_threshold(count: int, span_s: float) -> None:
    assert compute_rate_hz(count=count, span_s=span_s) is None


# --- resolve_message_name ---------------------------------------------------

# Seen on real hardware during the first P1-00 run, and previously printed as
# bare numeric IDs. The expected names are asserted against pymavlink's dialect
# rather than trusted from the incident report.
HARDWARE_MESSAGE_IDS = [77, 111, 152, 163, 178, 226, 245, 281, 285, 11039]


@pytest.mark.parametrize("msgid", HARDWARE_MESSAGE_IDS)
def test_hardware_message_ids_resolve_to_names(msgid: int) -> None:
    name = resolve_message_name(msgid)

    assert name == mav2.mavlink_map[msgid].msgname
    assert not name.startswith("#"), f"{msgid} still reports as a bare ID"


@pytest.mark.parametrize("msgid", sorted(REQUIRED_STREAMS | EVENT_DRIVEN))
def test_pipeline_messages_resolve_consistently(msgid: int) -> None:
    """The static fallback must agree with the dialect, not contradict it."""
    assert resolve_message_name(msgid) == mav2.mavlink_map[msgid].msgname
    assert MESSAGE_NAMES[msgid] == mav2.mavlink_map[msgid].msgname


def test_unknown_id_falls_back_to_a_bare_marker() -> None:
    unknown = 64999
    assert unknown not in mav2.mavlink_map

    assert resolve_message_name(unknown) == f"#{unknown}"


# --- source classification --------------------------------------------------


def heartbeat_from(
    mav_type: int, autopilot: int, sysid: int = SYSID, compid: int = COMPID
) -> bytes:
    link = _v2_link(sysid, compid)
    message = mav2.MAVLink_heartbeat_message(
        type=mav_type,
        autopilot=autopilot,
        base_mode=0,
        custom_mode=0,
        system_status=mav2.MAV_STATE_STANDBY,
        mavlink_version=3,
    )
    return bytes(message.pack(link))


def test_heartbeat_field_order_is_what_the_offsets_assume() -> None:
    """Pin the layout against the reference, as for PARAM_VALUE.

    If MAVLink's field ordering is ever misremembered, this says what the real
    layout is instead of letting a plausible-looking byte be read as a type.
    """
    ordered = mav2.mavlink_map[0].ordered_fieldnames

    assert ordered[0] == "custom_mode"  # uint32, sorts first
    assert ordered[1] == "type"
    assert ordered[2] == "autopilot"


def test_heartbeat_offsets_match_the_reference_encoder() -> None:
    """custom_mode occupies 4 bytes, so type is at 4 and autopilot at 5."""
    frame = heartbeat_from(mav2.MAV_TYPE_GCS, mav2.MAV_AUTOPILOT_INVALID)
    payload = payload_of(frame)

    assert payload is not None
    assert len(payload) == HEARTBEAT_PAYLOAD_LEN
    assert payload[4] == mav2.MAV_TYPE_GCS
    assert payload[5] == mav2.MAV_AUTOPILOT_INVALID


def test_enum_constants_match_the_reference() -> None:
    assert MAV_TYPE_GCS == mav2.MAV_TYPE_GCS
    assert MAV_AUTOPILOT_INVALID == mav2.MAV_AUTOPILOT_INVALID


@pytest.mark.parametrize("msgid_name", sorted(NON_VEHICLE_MAV_TYPES))
def test_non_vehicle_types_exist_in_the_dialect(msgid_name: int) -> None:
    """Every value pinned here must be a real MAV_TYPE, not a typo."""
    known = {getattr(mav2, name) for name in dir(mav2) if name.startswith("MAV_TYPE_")}

    assert msgid_name in known


def test_parse_heartbeat_reads_type_and_autopilot() -> None:
    frame = heartbeat_from(mav2.MAV_TYPE_QUADROTOR, mav2.MAV_AUTOPILOT_ARDUPILOTMEGA)

    assert parse_heartbeat(frame) == (
        mav2.MAV_TYPE_QUADROTOR,
        mav2.MAV_AUTOPILOT_ARDUPILOTMEGA,
    )


def test_parse_heartbeat_rejects_a_truncated_frame() -> None:
    assert parse_heartbeat(heartbeat_from(mav2.MAV_TYPE_GCS, 0)[:-5]) is None


def test_a_ground_station_is_not_a_vehicle() -> None:
    """The case that prompted this: QGC audited for missing vehicle streams."""
    assert classify_source(mav2.MAV_TYPE_GCS, mav2.MAV_AUTOPILOT_INVALID) == "gcs"


def test_a_gcs_is_classified_by_type_not_by_sysid() -> None:
    """SYSID 255 is a convention and a user setting, not a guarantee.

    A ground station on SYSID 1 must still classify as a ground station, and a
    vehicle on SYSID 255 must still classify as a vehicle.
    """
    gcs = heartbeat_from(mav2.MAV_TYPE_GCS, mav2.MAV_AUTOPILOT_INVALID, sysid=1)
    vehicle = heartbeat_from(
        mav2.MAV_TYPE_QUADROTOR, mav2.MAV_AUTOPILOT_ARDUPILOTMEGA, sysid=255
    )

    gcs_identity = parse_heartbeat(gcs)
    vehicle_identity = parse_heartbeat(vehicle)
    assert gcs_identity is not None
    assert vehicle_identity is not None

    assert classify_source(*gcs_identity) == "gcs"
    assert classify_source(*vehicle_identity) == "vehicle"


def test_a_gimbal_is_a_component() -> None:
    """This airframe has one, and it heartbeats under the vehicle's SYSID."""
    assert classify_source(mav2.MAV_TYPE_GIMBAL, mav2.MAV_AUTOPILOT_INVALID) == (
        "component"
    )


def test_a_companion_computer_is_a_component() -> None:
    """From Stage 2 our own agent is one of these; it is not an aircraft."""
    assert (
        classify_source(mav2.MAV_TYPE_ONBOARD_CONTROLLER, mav2.MAV_AUTOPILOT_INVALID)
        == "component"
    )


def test_an_invalid_autopilot_means_a_component_whatever_the_type() -> None:
    """The MAVLink convention for a non-autopilot component."""
    assert classify_source(mav2.MAV_TYPE_GENERIC, mav2.MAV_AUTOPILOT_INVALID) == (
        "component"
    )


@pytest.mark.parametrize(
    "mav_type",
    [
        mav2.MAV_TYPE_QUADROTOR,
        mav2.MAV_TYPE_HEXAROTOR,
        mav2.MAV_TYPE_OCTOROTOR,
        mav2.MAV_TYPE_FIXED_WING,
        mav2.MAV_TYPE_VTOL_QUADROTOR,
        mav2.MAV_TYPE_HELICOPTER,
    ],
)
def test_airframes_are_vehicles(mav_type: int) -> None:
    assert classify_source(mav_type, mav2.MAV_AUTOPILOT_ARDUPILOTMEGA) == "vehicle"


def test_a_just_booted_vehicle_is_still_a_vehicle() -> None:
    """A vehicle that has sent only a HEARTBEAT must not be filtered out.

    Classifying on traffic volume rather than identity would hide an aircraft
    at exactly the moment it appears — which is why the heuristic is the
    HEARTBEAT payload and not the message inventory.
    """
    frame = heartbeat_from(mav2.MAV_TYPE_QUADROTOR, mav2.MAV_AUTOPILOT_ARDUPILOTMEGA)
    identity = parse_heartbeat(frame)

    assert identity is not None
    assert classify_source(*identity) == "vehicle"


def test_an_unknown_type_defaults_to_vehicle() -> None:
    """Ambiguity resolves towards the aircraft.

    Registering a ground station as an aircraft is a nuisance. Failing to
    register an aircraft is the direction that gets someone hurt.
    """
    unknown_type = 200
    assert unknown_type not in NON_VEHICLE_MAV_TYPES

    assert classify_source(unknown_type, mav2.MAV_AUTOPILOT_ARDUPILOTMEGA) == "vehicle"


def test_vehicle_and_gimbal_under_one_sysid_are_separate_sources() -> None:
    """Keyed on (sysid, compid): the gimbal shares SYSID 1 with the aircraft."""
    autopilot = heartbeat_from(
        mav2.MAV_TYPE_QUADROTOR, mav2.MAV_AUTOPILOT_ARDUPILOTMEGA, sysid=1, compid=1
    )
    gimbal = heartbeat_from(
        mav2.MAV_TYPE_GIMBAL, mav2.MAV_AUTOPILOT_INVALID, sysid=1, compid=154
    )

    autopilot_header = decode_header(autopilot)
    gimbal_header = decode_header(gimbal)
    assert autopilot_header is not None
    assert gimbal_header is not None

    # Same SYSID, different component: distinct sources.
    assert autopilot_header[0] == gimbal_header[0] == 1
    assert autopilot_header[1] != gimbal_header[1]

    autopilot_identity = parse_heartbeat(autopilot)
    gimbal_identity = parse_heartbeat(gimbal)
    assert autopilot_identity is not None
    assert gimbal_identity is not None

    assert classify_source(*autopilot_identity) == "vehicle"
    assert classify_source(*gimbal_identity) == "component"


def test_printed_output_is_ascii_only() -> None:
    """The probe's stdout is pasted into a decision record.

    A Windows console in cp1252 renders an em dash as a replacement character,
    so a non-ASCII literal reaches the ADR as mojibake. Comments and docstrings
    are unrestricted; only what is printed has to survive the trip.
    """
    source = Path(mavlink_probe.__file__).read_text(encoding="utf-8")
    offenders: list[str] = []

    for node in ast.walk(ast.parse(source)):
        if not (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "print"
        ):
            continue
        for literal in ast.walk(node):
            if (
                isinstance(literal, ast.Constant)
                and isinstance(literal.value, str)
                and not literal.value.isascii()
            ):
                offenders.append(f"line {literal.lineno}: {literal.value!r}")

    assert not offenders, "non-ASCII in printed output:\n" + "\n".join(offenders)


def test_resolution_does_not_warn() -> None:
    """`name` is deprecated and warns per access; `msgname` must be used.

    pytest runs with filterwarnings = ["error"], so a regression to `.name`
    fails here rather than quietly emitting thousands of warnings during a
    60-second capture.
    """
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        assert resolve_message_name(0) == "HEARTBEAT"
