"""Frame parsing in the probe, checked against frames pymavlink built.

No socket is opened anywhere in this file. Every frame is generated by
pymavlink and then handed to the probe's own parser, so the assertions compare
our reading of the wire format against the reference implementation rather than
against bytes someone typed out by hand.

That matters most for `extract_param_id`. MAVLink orders payload fields by
descending type size rather than declaration order, so the offset of param_id
is easy to get wrong and impossible to notice: a wrong offset yields a
plausible-looking string, the roundtrip probe never matches it, and the link
gets recorded as telemetry-only forever without anyone learning why.
"""

from __future__ import annotations

import pytest
from pymavlink.dialects.v10 import ardupilotmega as mav1
from pymavlink.dialects.v20 import ardupilotmega as mav2

from tools.mavlink_probe import (
    MAVLINK_V1_MAGIC,
    MAVLINK_V2_MAGIC,
    PARAM_VALUE_MSGID,
    decode_header,
    extract_param_id,
    payload_of,
    split_frames,
)

SYSID = 7
COMPID = 1


def _v2_link(sysid: int = SYSID, compid: int = COMPID) -> mav2.MAVLink:
    link = mav2.MAVLink(None, srcSystem=sysid, srcComponent=compid)
    link.signing.sign_outgoing = False
    return link


def _v1_link(sysid: int = SYSID, compid: int = COMPID) -> mav1.MAVLink:
    return mav1.MAVLink(None, srcSystem=sysid, srcComponent=compid)


def heartbeat_v2(sysid: int = SYSID) -> bytes:
    link = _v2_link(sysid)
    message = mav2.MAVLink_heartbeat_message(
        type=mav2.MAV_TYPE_QUADROTOR,
        autopilot=mav2.MAV_AUTOPILOT_ARDUPILOTMEGA,
        base_mode=0,
        custom_mode=0,
        system_status=mav2.MAV_STATE_STANDBY,
        mavlink_version=3,
    )
    return bytes(message.pack(link))


def heartbeat_v1(sysid: int = SYSID) -> bytes:
    link = _v1_link(sysid)
    message = mav1.MAVLink_heartbeat_message(
        type=mav1.MAV_TYPE_QUADROTOR,
        autopilot=mav1.MAV_AUTOPILOT_ARDUPILOTMEGA,
        base_mode=0,
        custom_mode=0,
        system_status=mav1.MAV_STATE_STANDBY,
        mavlink_version=3,
    )
    return bytes(message.pack(link))


def param_value_v2(param_id: str, sysid: int = SYSID) -> bytes:
    link = _v2_link(sysid)
    message = mav2.MAVLink_param_value_message(
        param_id=param_id.encode("ascii"),
        param_value=1.0,
        param_type=mav2.MAV_PARAM_TYPE_INT32,
        param_count=800,
        param_index=42,
    )
    return bytes(message.pack(link))


def param_value_v1(param_id: str, sysid: int = SYSID) -> bytes:
    link = _v1_link(sysid)
    message = mav1.MAVLink_param_value_message(
        param_id=param_id.encode("ascii"),
        param_value=1.0,
        param_type=mav1.MAV_PARAM_TYPE_INT32,
        param_count=800,
        param_index=42,
    )
    return bytes(message.pack(link))


def sign_v2_frame(frame: bytes) -> bytes:
    """Set the signing flag and append a 13-byte signature block.

    The probe never validates a signature; it only has to account for the extra
    bytes when deciding where a frame ends. A block of the right length is
    therefore a faithful fixture for the only property under test.
    """
    body = bytearray(frame)
    body[2] |= 0x01  # incompat_flags: MAVLINK_IFLAG_SIGNED
    return bytes(body) + bytes(range(13))


# --- split_frames -----------------------------------------------------------


def test_single_frame_round_trips() -> None:
    frame = heartbeat_v2()

    assert split_frames(frame) == [frame]


def test_multi_frame_datagram_is_split_exactly() -> None:
    """QGC coalesces several MAVLink frames into one UDP datagram."""
    first = heartbeat_v2(sysid=1)
    second = param_value_v2("SYSID_THISMAV", sysid=2)
    third = heartbeat_v1(sysid=3)

    assert split_frames(first + second + third) == [first, second, third]


def test_truncated_trailing_frame_is_dropped_not_guessed() -> None:
    """A short final frame must be discarded, and the whole ones kept."""
    whole = heartbeat_v2()
    truncated = param_value_v2("SYSID_THISMAV")[:-4]

    assert split_frames(whole + truncated) == [whole]


def test_truncated_frame_alone_yields_nothing() -> None:
    assert split_frames(heartbeat_v2()[:-1]) == []


def test_signed_v2_frame_length_accounts_for_the_signature() -> None:
    """The signing flag adds 13 bytes; miscounting them desynchronises the rest."""
    signed = sign_v2_frame(heartbeat_v2(sysid=1))
    following = heartbeat_v2(sysid=2)

    assert split_frames(signed + following) == [signed, following]


def test_garbage_before_a_valid_frame_is_resynchronised() -> None:
    frame = heartbeat_v2()

    assert split_frames(b"\x00\x11\x22garbage" + frame) == [frame]


def test_garbage_only_yields_nothing() -> None:
    assert split_frames(b"no mavlink here") == []


def test_empty_input_yields_nothing() -> None:
    assert split_frames(b"") == []


# --- decode_header ----------------------------------------------------------


def test_decode_header_v2() -> None:
    header = decode_header(param_value_v2("SYSID_THISMAV", sysid=11))

    assert header == (11, COMPID, PARAM_VALUE_MSGID)


def test_decode_header_v1() -> None:
    header = decode_header(param_value_v1("SYSID_THISMAV", sysid=11))

    assert header == (11, COMPID, PARAM_VALUE_MSGID)


def test_decode_header_v1_and_v2_agree() -> None:
    """Version must not change the identity the Gateway keys vehicles on."""
    assert decode_header(heartbeat_v1(sysid=5)) == decode_header(heartbeat_v2(sysid=5))


def test_decode_header_on_signed_frame() -> None:
    signed = sign_v2_frame(param_value_v2("SYSID_THISMAV", sysid=9))

    assert decode_header(signed) == (9, COMPID, PARAM_VALUE_MSGID)


@pytest.mark.parametrize("length", [0, 1, 5, 7])
def test_decode_header_rejects_short_input(length: int) -> None:
    assert decode_header(heartbeat_v2()[:length]) is None


def test_decode_header_rejects_unknown_magic() -> None:
    assert decode_header(b"\x00" * 16) is None


# --- payload_of -------------------------------------------------------------


def test_payload_of_v2_matches_the_declared_length() -> None:
    frame = param_value_v2("SYSID_THISMAV")

    payload = payload_of(frame)

    assert payload is not None
    assert len(payload) == frame[1]


def test_payload_of_signed_frame_excludes_the_signature() -> None:
    """Slicing back from the end would swallow signature bytes as payload."""
    unsigned = param_value_v2("SYSID_THISMAV")
    signed = sign_v2_frame(unsigned)

    assert payload_of(signed) == payload_of(unsigned)


def test_payload_of_rejects_a_truncated_payload() -> None:
    assert payload_of(param_value_v2("SYSID_THISMAV")[:-6]) is None


def test_payload_of_rejects_unknown_magic() -> None:
    assert payload_of(b"\x01\x02\x03\x04") is None


# --- extract_param_id -------------------------------------------------------

PARAM_NAMES = [
    "SYSID_THISMAV",
    "BATT_CAPACITY",
    "A",  # shortest plausible name
    "FENCE_ALT_MAX",
    "RTL_ALT",
]


@pytest.mark.parametrize("name", PARAM_NAMES)
def test_extract_param_id_v2(name: str) -> None:
    assert extract_param_id(param_value_v2(name)) == name


@pytest.mark.parametrize("name", PARAM_NAMES)
def test_extract_param_id_v1(name: str) -> None:
    assert extract_param_id(param_value_v1(name)) == name


def test_extract_param_id_v1_and_v2_agree() -> None:
    name = "SYSID_THISMAV"

    assert extract_param_id(param_value_v1(name)) == extract_param_id(
        param_value_v2(name)
    )


def test_extract_param_id_handles_a_full_16_character_name() -> None:
    """A name filling the field has no NUL terminator to stop at."""
    name = "ABCDEFGHIJKLMNOP"
    assert len(name) == 16

    assert extract_param_id(param_value_v2(name)) == name


def test_extract_param_id_survives_v2_payload_truncation() -> None:
    """v2 trims trailing zero bytes; the parser must restore them."""
    frame = bytearray(param_value_v2("RTL_ALT"))
    # Drop the trailing zero bytes the way an encoder doing full truncation
    # would, leaving a payload shorter than the 25-byte PARAM_VALUE definition.
    payload_len = frame[1]
    assert payload_len >= 24

    assert extract_param_id(bytes(frame)) == "RTL_ALT"


def test_extract_param_id_on_signed_frame() -> None:
    signed = sign_v2_frame(param_value_v2("SYSID_THISMAV"))

    assert extract_param_id(signed) == "SYSID_THISMAV"


def test_extract_param_id_returns_none_for_non_ascii() -> None:
    """An unreadable name is a failure, never a wildcard match."""
    frame = bytearray(param_value_v2("SYSID_THISMAV"))
    frame[10 + 8] = 0xFF  # first byte of param_id

    assert extract_param_id(bytes(frame)) is None


def test_extract_param_id_returns_none_for_an_empty_name() -> None:
    frame = bytearray(param_value_v2("SYSID_THISMAV"))
    for offset in range(8, 24):
        frame[10 + offset] = 0x00

    assert extract_param_id(bytes(frame)) is None


def test_extract_param_id_returns_none_on_a_truncated_frame() -> None:
    assert extract_param_id(param_value_v2("SYSID_THISMAV")[:-6]) is None


def test_param_id_offset_matches_the_reference_encoder() -> None:
    """Pin the offset itself, not just the round trip.

    If MAVLink's field ordering is ever misremembered again, this fails with a
    message that says what the real layout is.
    """
    name = "SYSID_THISMAV"
    payload = payload_of(param_value_v2(name))

    assert payload is not None
    assert payload.index(name.encode("ascii")) == 8, (
        "param_id does not start at offset 8; MAVLink orders payload fields by "
        "descending type size, so re-derive the layout before changing the "
        "constants in mavlink_probe.py"
    )


# --- the parsers agree with each other --------------------------------------


def test_param_value_survives_a_realistic_coalesced_datagram() -> None:
    """The end-to-end path roundtrip mode depends on, without a socket."""
    datagram = (
        heartbeat_v2(sysid=1)
        + param_value_v2("SYSID_THISMAV", sysid=1)
        + heartbeat_v1(sysid=2)
    )

    names = [
        extract_param_id(frame)
        for frame in split_frames(datagram)
        if (header := decode_header(frame)) is not None
        and header[2] == PARAM_VALUE_MSGID
    ]

    assert names == ["SYSID_THISMAV"]


def test_magic_constants_match_the_reference_encoder() -> None:
    assert heartbeat_v2()[0] == MAVLINK_V2_MAGIC
    assert heartbeat_v1()[0] == MAVLINK_V1_MAGIC
