"""The core API: the fleet registry and its audit log. P2-05, P2-06.

Orders and pricing (P2-03, P2-04, P2-07) are not here: they are the courier
business, and that decision is open (2026-09-28).

**There is no operator authentication yet.** Nothing in TASKS.md provides it,
so the API binds to loopback by default and must not be exposed until it
does. Every change is recorded in `events` with `actor_type = 'api'`, so the
trail is complete now and attributable later.

The OpenAPI schema is generated by FastAPI at `/openapi.json`; TypeScript
types are generated from it (CLAUDE.md), never written by hand.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field

from api.registry import (
    AirframeParams,
    ConflictError,
    DroneStatus,
    FleetRegistry,
    NotFoundError,
    PilotStatus,
    RegistryError,
)

MAX_EVENTS_PER_PAGE = 1_000


class BaseIn(BaseModel):
    name: str = Field(min_length=1)
    lat_deg: float = Field(ge=-90, le=90)
    lon_deg: float = Field(ge=-180, le=180)
    elevation_amsl_m: float | None = None
    capacity: int = Field(default=0, ge=0)
    charging_slots: int = Field(default=0, ge=0)


class BaseOut(BaseModel):
    id: UUID
    name: str
    lat_deg: float
    lon_deg: float
    elevation_amsl_m: float | None
    capacity: int
    charging_slots: int
    created_at: datetime


class PilotIn(BaseModel):
    name: str = Field(min_length=1)
    license_ref: str | None = None
    max_concurrent_drones: int = Field(default=1, ge=1)


class PilotOut(BaseModel):
    id: UUID
    name: str
    license_ref: str | None
    status: PilotStatus
    max_concurrent_drones: int
    created_at: datetime


class PilotStatusIn(BaseModel):
    status: PilotStatus


class DroneIn(BaseModel):
    serial: str = Field(min_length=1)
    label: str = Field(min_length=1)
    model: str | None = None
    max_payload_g: int | None = Field(default=None, gt=0)
    max_range_m: float | None = Field(default=None, gt=0)
    battery_capacity_wh: float | None = Field(default=None, gt=0)
    cruise_speed_ms: float | None = Field(default=None, gt=0)
    avg_power_w: float | None = Field(default=None, gt=0)
    home_base_id: UUID | None = None
    current_pilot_id: UUID | None = None


class DroneOut(BaseModel):
    id: UUID
    serial: str
    label: str
    model: str | None
    max_payload_g: int | None
    max_range_m: float | None
    battery_capacity_wh: float | None
    cruise_speed_ms: float | None
    avg_power_w: float | None
    home_base_id: UUID | None
    current_pilot_id: UUID | None
    in_maintenance: bool
    retired_at: datetime | None
    created_at: datetime
    # Derived from telemetry on every read; see `api.registry.derive_status`.
    status: DroneStatus


class MaintenanceIn(BaseModel):
    in_maintenance: bool


class EventOut(BaseModel):
    id: int
    ts: datetime
    actor_type: str
    actor_id: str | None
    entity_type: str
    entity_id: str
    event_type: str
    payload: dict[str, Any]


def _http(error: RegistryError) -> HTTPException:
    if isinstance(error, NotFoundError):
        return HTTPException(status_code=404, detail=str(error))
    if isinstance(error, ConflictError):
        return HTTPException(status_code=409, detail=str(error))
    return HTTPException(status_code=400, detail=str(error))


def create_api_app(registry: FleetRegistry) -> FastAPI:
    app = FastAPI(title="courier API", version="0.1.0")

    # --- bases ----------------------------------------------------------------

    @app.post("/bases", response_model=BaseOut, status_code=201)
    async def create_base(body: BaseIn) -> dict[str, Any]:
        try:
            return await registry.create_base(**body.model_dump())
        except RegistryError as error:
            raise _http(error) from error

    @app.get("/bases", response_model=list[BaseOut])
    async def list_bases() -> list[dict[str, Any]]:
        return await registry.list_bases()

    # --- pilots ---------------------------------------------------------------

    @app.post("/pilots", response_model=PilotOut, status_code=201)
    async def create_pilot(body: PilotIn) -> dict[str, Any]:
        try:
            return await registry.create_pilot(**body.model_dump())
        except RegistryError as error:
            raise _http(error) from error

    @app.get("/pilots", response_model=list[PilotOut])
    async def list_pilots() -> list[dict[str, Any]]:
        return await registry.list_pilots()

    @app.put("/pilots/{pilot_id}/status", response_model=PilotOut)
    async def set_pilot_status(pilot_id: UUID, body: PilotStatusIn) -> dict[str, Any]:
        try:
            return await registry.set_pilot_status(pilot_id, body.status)
        except RegistryError as error:
            raise _http(error) from error

    # --- drones ---------------------------------------------------------------

    @app.post("/drones", response_model=DroneOut, status_code=201)
    async def register_drone(body: DroneIn) -> dict[str, Any]:
        fields = body.model_dump()
        params = AirframeParams(
            max_payload_g=fields.pop("max_payload_g"),
            max_range_m=fields.pop("max_range_m"),
            battery_capacity_wh=fields.pop("battery_capacity_wh"),
            cruise_speed_ms=fields.pop("cruise_speed_ms"),
            avg_power_w=fields.pop("avg_power_w"),
        )
        try:
            return await registry.register_drone(params=params, **fields)
        except RegistryError as error:
            raise _http(error) from error

    @app.get("/drones", response_model=list[DroneOut])
    async def list_drones(include_retired: bool = False) -> list[dict[str, Any]]:
        return await registry.list_drones(include_retired=include_retired)

    @app.get("/drones/{drone_id}", response_model=DroneOut)
    async def get_drone(drone_id: UUID) -> dict[str, Any]:
        try:
            return await registry.get_drone(drone_id)
        except RegistryError as error:
            raise _http(error) from error

    @app.put("/drones/{drone_id}/maintenance", response_model=DroneOut)
    async def set_maintenance(drone_id: UUID, body: MaintenanceIn) -> dict[str, Any]:
        try:
            return await registry.set_maintenance(drone_id, body.in_maintenance)
        except RegistryError as error:
            raise _http(error) from error

    @app.post("/drones/{drone_id}/retire", response_model=DroneOut)
    async def retire_drone(drone_id: UUID) -> dict[str, Any]:
        try:
            return await registry.retire_drone(drone_id)
        except RegistryError as error:
            raise _http(error) from error

    # --- audit (P2-06) --------------------------------------------------------

    @app.get("/events", response_model=list[EventOut])
    async def events(
        entity_type: str | None = None,
        entity_id: str | None = None,
        since: datetime | None = None,
        until: datetime | None = None,
        after_id: int | None = None,
        limit: int = Query(default=500, ge=1, le=MAX_EVENTS_PER_PAGE),
    ) -> list[dict[str, Any]]:
        """Filter by entity and time; page with `after_id` = the last `id` seen."""
        return await registry.events(
            entity_type=entity_type,
            entity_id=entity_id,
            since=since,
            until=until,
            after_id=after_id,
            limit=limit,
        )

    return app
